#!/bin/tcsh

#---
# Creates field map from a set of images acquired using the 2dfast pulse sequence
# Meant to replace Ollinger's make_fmap
#---

set fmap_dir = $argv[1] #s11_fmap
set file_out = $argv[2] #FmapAFNI.nii


dcm2niix_afni $fmap_dir

#cd $fmap_dir

#--- may need to swap the two ---
set file1 = `ls $fmap_dir/*nii | head -1`
set file2 = `ls $fmap_dir/*nii | tail -1`
echo "file1: $file1"
echo "file2: $file2"

set dte = 3

#---
# sub-brick 0 = magnitude
# sub-brick 1 = phase
# sub-brick 2 = real
# sub-brick 3 = imaginary
#---

COMPUTE_PHASE:
3dcalc -a $file1'[2]' -b $file1'[3]' -c $file2'[2]' -d $file2'[3]' \
       -expr "atan2((b*c-d*a),(a*c+b*d))" \
       -prefix tmp.phase_diff.$file_out

COMPUTE_MAG:       
3dcalc -a $file1'[0]' -expr 'a' -prefix tmp.mag.$file_out
       
UNWRAP_PHASE:
prelude -p tmp.phase_diff.$file_out -a tmp.mag.$file_out -o tmp.phase_diff.unwrap.$file_out

CONVERT_TO_HZ:
3dcalc -a tmp.phase_diff.unwrap.$file_out -expr "a*1000/$dte" -prefix $file_out

CLEANUP:
if (-e $file_out) then
   rm -f tmp.phase_diff.unwrap.$file_out.gz
   rm -f tmp.phase_diff.$file_out
   rm -f tmp.mag.$file_out
endif
